server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: dousheng-auth
          uri: lb://dousheng-auth
          predicates:
            - Path=/dousheng-auth/**
          filters:
            - StripPrefix=1
        - id: dousheng-admin
          uri: lb://dousheng-admin
          predicates:
            - Path=/dousheng-admin/**
          filters:
            - StripPrefix=1
        - id: dousheng-portal
          uri: lb://dousheng-portal
          predicates:
            - Path=/dousheng-portal/**
          filters:
            - StripPrefix=1
        - id: dousheng-search
          uri: lb://dousheng-search
          predicates:
            - Path=/dousheng-search/**
          filters:
            - StripPrefix=1
        - id: dousheng-video
          uri: lb://dousheng-video
          predicates:
            - Path=/dousheng-video/**
          filters:
            - StripPrefix=1
#        - id: dousheng-demo
#          uri: lb://dousheng-demo
#          predicates:
#            - Path=/dousheng-demo/**
#          filters:
#            - StripPrefix=1
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: 'http://localhost:8201/dousheng-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/dousheng-auth/oauth/token"
      - "/dousheng-auth/rsa/publicKey"
      - "/dousheng-search/**"
      - "/dousheng-portal/sso/login"
      - "/dousheng-portal/sso/register"
      - "/dousheng-portal/sso/getAuthCode"
      - "/dousheng-portal/home/**"
      - "/dousheng-portal/product/**"
      - "/dousheng-portal/brand/**"
      - "/dousheng-admin/admin/login"
      - "/dousheng-admin/admin/register"
      - "/dousheng-admin/minio/upload"
      - "/douyin/**"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
